# Generated by Django 4.2.1 on 2025-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_subproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
