# Generated by Django 4.2.1 on 2025-11-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_product_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
